easy_admin:
    site_name: 'Darbo skelbimų portalas'
    design:
        menu:
            - {entity: Vartotojas, label: "Vartotojai", icon: "user", permission: 'ROLE_ADMIN'}
            - {entity: Skelbimas, label: "Skelbimai"}
    entities:
        Skelbimas:
            class: App\Entity\Skelbimas
            controller: App\Controller\SkelbimasController
            list:
                actions:
                    - show
                    - -delete
                fields:
                    - id
                    - tipas
                    - pavadinimas
                    - pridejimo_data
                    - galiojimo_pab
            form:
                fields:
                    - pavadinimas
                    - {property: tipas, type: choice, type_options: {choices: {'Ieškau':'Ieškau', 'Siūlau':'Siūlau'} } }
                    - {property: aprasymas, type: textarea}
                    - galiojimo_pab
                    - vartotojas
            show:
                fields:
                    - id
                    - tipas
                    - pridejimo_data
                    - galiojimo_pab
                    - {property: vartotojas, type: string}
                    - pavadinimas
                    - aprasymas
        Vartotojas:
            class: App\Entity\Vartotojas
            form:
                fields:
                    - slapyvardis
                    - password
                    - {property: ar_gali_deti, type: checkbox, label: "Ar gali dėti skelbimus?"}
            list:
                actions:
                    - edit
                    - delete
                fields:
                    - id
                    - slapyvardis
                    - skelbimai
