easy_admin:
    site_name: 'Darbo skelbimų portalas'
    design:
        menu:
            - {entity: Vartotojas, label: "Vartotojai", icon: "user", permission: 'ROLE_ADMIN'}
            - {entity: Skelbimas, label: "Skelbimai"}
    entities:
        Skelbimas:
            class: App\Entity\Skelbimas
            controller: App\Controller\SkelbimasController
            list:
                actions:
                    - show
                    - -delete
                fields:
                    - id
                    - pavadinimas
                    - pridejimo_data
                    - galiojimo_pab
            form:
                fields:
                    - pavadinimas
                    - { property: aprasymas, type: textarea }
                    - galiojimo_pab
                    - vartotojas
            show:
                fields:
                    - id
                    - pridejimo_data
                    - galiojimo_pab
                    - {property: vartotojas, type: string}
                    - pavadinimas
                    - aprasymas
        Vartotojas:
            class: App\Entity\Vartotojas
            form:
                fields:
                    - slapyvardis
                    - password
